apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-bootstrap-tcpfront-config
  namespace: default
data:
  envoy.yaml: |
    # Author: MageEdu <mage@magedu.com>
    # Site: www.magedu.com
    admin:
      profile_path: /tmp/envoy.prof
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
           address: 0.0.0.0
           port_value: 9901

    static_resources:
      listeners:
        name: listener_0
        address:
          socket_address: { address: 0.0.0.0, port_value: 80 }
        filter_chains:
        - filters:
          - name: envoy.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: tcp
              cluster: local_cluster

      clusters:
      - name: local_cluster
        connect_timeout: 0.25s
        type: STATIC
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: local_cluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address: { address: 10.100.1.254, port_value: 80 }
            - endpoint:
                address:
                  socket_address: { address: 10.100.2.66, port_value: 80 }
